# fly.toml app configuration file generated for alinegrance-alpha-blog on 2023-08-24T14:53:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alinegrance-alpha-blog"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[build]

[env]
  DATABASE_URL = "sqlite3:///data/production.sqlite3"

[[mounts]]
  source = "alpha_blog_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
